name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello !!"
      - name: Say Bye
        run: echo "Bye !!"
      - name: Multiple line command
        run: |
            echo "This is line one"
            echo "This is line two"
